In [56]:
import numpy as np
import pandas as pd

import sys
sys.path.insert(0, '/home/563/dy2988/statistical_enso')
from prediction_analysis_Dine import brier_skill_score
sys.path.insert(0, '/home/563/dy2988/statistical_enso/data/synthetic_test')
from compute_bss import brier_skill
from compute_leps import leps_skill

In [36]:
ds = pd.read_csv('/home/563/dy2988/statistical_enso/data/synthetic_test/case1_hand_check.csv')
answers = pd.read_csv('/home/563/dy2988/statistical_enso/data/synthetic_test/answer_key.csv')

In [37]:
ds

   year  p_below  p_normal  p_above     obs  o_below  o_normal  o_above
0  2001      0.5       0.3      0.2   below        1         0        0
1  2002      0.2       0.5      0.3  normal        0         1        0
2  2003      0.1       0.3      0.6   above        0         0        1
3  2004      0.4       0.4      0.2   above        0         0        1
4  2005      0.6       0.3      0.1   below        1         0        0
5  2006      0.3       0.3      0.4  normal        0         1        0

In [38]:
# extract proba
# extract obs

proba_df = ds[['p_below', 'p_normal', 'p_above']]
obs_df = ds[['obs']]

In [54]:
answers

,dataset,n,n_below,n_normal,n_above,BS_multi,BSref_fixed_multi,BSS_fixed_multi,BSref_sample_multi,BSS_sample_multi,...,BSref_sample_normal,BSS_sample_normal,BS_above,BSref_fixed_above,BSS_fixed_above,BSref_sample_above,BSS_sample_above,RPS,RPSref_fixed,RPSS_fixed
0,case1_hand_check,6,2,2,2,0.496667,0.666667,0.255000,0.666667,0.255000,...,0.222222,0.122500,0.183333,0.222222,0.175000,0.222222,0.175000,0.301667,0.444444,0.321250
1,case2_perfect,30,10,10,10,0.000000,0.666667,1.000000,0.666667,1.000000,...,0.222222,1.000000,0.000000,0.222222,1.000000,0.222222,1.000000,0.000000,0.444444,1.000000
2,case3_climatology,30,10,10,10,0.666733,0.666667,-0.000100,0.666667,-0.000100,...,0.222222,-0.000050,0.222267,0.222222,-0.000200,0.222222,-0.000200,0.444500,0.444444,-0.000125
3,case4_always_wrong,30,10,10,10,2.000000,0.666667,-2.000000,0.666667,-2.000000,...,0.222222,-2.000000,0.666667,0.222222,-2.000000,0.222222,-2.000000,1.333333,0.444444,-2.000000
4,case5_realistic_40yr,40,13,13,14,0.532130,0.666667,0.201805,0.666250,0.201306,...,0.219375,0.047829,0.178045,0.227778,0.218339,0.227500,0.217385,0.323248,0.447222,0.277211
5,case6_imbalanced,30,14,9,7,0.502500,0.666667,0.246250,0.637778,0.212108,...,0.210000,0.267857,0.150583,0.188889,0.202794,0.178889,0.158230,0.348750,0.455556,0.234451

In [51]:
obs = obs_df['obs'].replace({
    'below': 0,
    'normal': 1,
    'above': 2
}).to_numpy()
proba = proba_df[['p_below', 'p_normal', 'p_above']].to_numpy()

test_run = brier_skill_score(obs, proba)
test_run

/jobfs/180846614.gadi-pbs/ipykernel_1858408/1168497822.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  obs = obs_df['obs'].replace({

np.float64(0.25499999999999995)

In [46]:
proba

array([[0.5, 0.3, 0.2],
       [0.2, 0.5, 0.3],
       [0.1, 0.3, 0.6],
       [0.4, 0.4, 0.2],
       [0.6, 0.3, 0.1],
       [0.3, 0.3, 0.4]])

In [53]:
print(obs)

obs_onehot = np.eye(3, dtype=int)[obs]
print(obs_onehot)

[0 1 2 2 0 1]
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]]

In [55]:
test_run2 = brier_skill (proba,obs_onehot)
test_run2

{'BS': np.float64(0.4966666666666667),
 'BSref': np.float64(0.6666666666666667),
 'BSS': np.float64(0.255),
 'BS_k': array([0.11833333, 0.195     , 0.18333333]),
 'BSref_k': array([0.22222222, 0.22222222, 0.22222222]),
 'BSS_k': array([0.4675, 0.1225, 0.175 ])}

In [ ]:
'''
ARGUMENTS:
        y_obs: array[n] of classes observed
        probabilities: array[n,3] of probabilities to be in class (0 to 2) for n observations
            NB: predictions can be inferred from this, but aren't necessary here




def leps_skill(P, j):
    """Correct LEPS skill."""
    s = (P * M[:, j].T).sum(axis=1)       # s_i = sum_k p_k M[k, j_i]
    u = U[j]
    l = L[j]
    S = s.sum()
    denom = u.sum() if S >= 0 else abs(l.sum())
    return {"s": s, "mean_S": s.mean(), "sum_S": S, "sum_S_m": denom, "LEPS_skill": S / denom}

            '''